### ISSUE TITLE
Item quality attribute

### ISSUE THREAD

**Issue by dirtboggle** [ASharpPen/Valheim.DropThat#19]
Please consider adding an item quality attribute. I'd like for bosses to drop a maximum quality item.

**Comment by ASharpPen** [comment]
Hm, looks easier than expected. Will add to todo

**Comment by ASharpPen** [comment]
Wrong. Not easy at all.

Diving deep.

**Comment by ASharpPen** [comment]
Giving up. Only the prefab GameObject is carried to the actual instantiation.

There is simply no reference that I can use to identify that the gameobject being spawned, is associated with a specific configuration for a mob. And since the gameobject is sealed, I can't even wrap it.
All modifications done to the prefab have consequences across the game, so can't simply change that either.

I would need to completely rewrite the logic for dropping items, to support this specific feature, which would most likely disturb a lot of other mods.
