### ISSUE TITLE
Question/Enhancement: Auto generate tables

### ISSUE THREAD

**Issue by Magnymbus** [ASharpPen/Valheim.DropThat#37]
It would be nice if the tables automatically added all drops to .tables.cfg if they don't already exist.
If this is already possible, how do? Is issue #28 related to this, preventing it from working? (description of #28 was ambiguous.)

**Comment by ASharpPen** [comment]
Its not related to #28. That one might not even be real but just me being tired and out of coffee.
Tables not being generated is due to the problem of identifying the actual tables in the first place.
I am doing it live atm, where whenever you get close to a mob, the drops gets modified.

I think I have an idea of how to improve this though. I will look into your request.

**Comment by Magnymbus** [comment]
That would be great. It would just be a whole lot easier to configure and compare if drop_that.tables.cfg already had all the preexisting drops listed. Even if it's something you had to do on the fly with the console, being able to see or look up the drops from a given creature in the same format as the config for this mod would make things much easier.

**Comment by ASharpPen** [comment]
I will see if I can do a file dump of all existing creature drop tables today, in a way where they can be copy-pasted directly into a drop that config file.

Might even be worth pre-populating the tables.cfg, if it works well. Will consider a toggle for enabling that on file creation.

**Comment by Magnymbus** [comment]
Nice!
