### ISSUE TITLE
Unable to get it to work

### ISSUE THREAD

**Issue by Ectso** [ASharpPen/Valheim.DropThat#8]
I've done some extensive table editing and no matter what I do, I cant seem to get it to work, even following the examples. Are there any specifics to this, does the integer for the chance to drop need to be formatted in a specific way if it's less than one? IE Chance = 0.10f or .1 or something else?

The indexes I've created all start at 0 and go from there, should I be starting them at a later number if the mob already has drops or something?

**Comment by ASharpPen** [comment]
Post your config and lets take a look.

The chance should be something like
```
Chance = 1
Chance = 0.5
Chance = 1.0
```

**Comment by Ectso** [comment]
[Greyling.0]
ItemName = Raspberry
AmountMin = 1
AmountMax = 2
Chance = 0.10
OnePerPlayer = false
LevelMultiplier = true
Enabled = true

﻿[Greydwarf.0]
ItemName = Blueberry
AmountMin = 1
AmountMax = 2
Chance = 0.10
OnePerPlayer = false
LevelMultiplier = true
Enabled = true

[Greydwarf.1]
ItemName = Thistle
AmountMin = 1
AmountMax = 1
Chance = 0.10
OnePerPlayer = false
LevelMultiplier = true
Enabled = true

﻿[Greydwarf_Shaman.0]
ItemName = Carrot
AmountMin = 1
AmountMax = 2
Chance = 0.25
OnePerPlayer = false
LevelMultiplier = true
Enabled = true

**Comment by Ectso** [comment]
[drop_that.tables.cfg.txt](https://github.com/ASharpPen/Valheim.DropThat/files/6065699/drop_that.tables.cfg.txt)

That's my current table config file.

**Comment by ASharpPen** [comment]
Ah, I think I found the issue. You can't comment out sections like you do.
Remove all the sections with "?[header]" and it should have an easier time loading. Several of your configs are already applied, but it has trouble with things like the Greyling due to following section.

Also, with regards to indexing, if you just want to add things you can either toggle "AlwaysAppend" in "drop_that.cfg" or simply set a high index
``` INI
[Greyling.100]
...
[Greyling.101]
```

**Comment by ASharpPen** [comment]
Closing due to no follow-up
